name: Deploy

on:
  push:
    branches:
      - main

    paths:
      - "apps/api/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/api"
          wranglerVersion: "* -w"
          packageManager: "pnpm"
          environment: "production"
          command: "deploy"
